#!/bin/sh

DAEMON4="/myApplications/startBluetooth.sh"
test -f ${DAEMON4} || exit 0

startdaemon4(){
  start-stop-daemon -b --start --quiet --exec ${DAEMON4}
  echo "${DAEMON4} started."
}

stopdaemon4(){
  start-stop-daemon --stop --quiet --exec ${DAEMON4}
  echo "${DAEMON4} stopped."
}

case "$1" in
  start)
	startdaemon4
      ;;
  stop)
	stopdaemon4
      ;;
  force-reload)
	stopdaemon4
	startdaemon4
      ;;
  restart)
	stopdaemon4
	startdaemon4
      ;;
  *)
      echo "Usage: $0 { start | stop | restart}" >&2
      exit 1
      ;;
esac
